# Generated by Django 2.1 on 2018-09-03 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('numero', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('portaria', models.FileField(blank=True, null=True, upload_to='portarias')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campi.Campus')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portaria',
            unique_together={('numero', 'ano', 'origem')},
        ),
    ]
