# Generated by Django 2.1 on 2018-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('numero', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ano', models.SmallIntegerField()),
                ('origem', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portaria',
            unique_together={('numero', 'ano', 'origem')},
        ),
    ]
