# Generated by Django 2.1 on 2018-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portarias', '0001_initial'),
        ('estagioProbatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagioprobatorio',
            name='portaria_homologacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portarias.Portaria'),
        ),
    ]
