# Generated by Django 2.1 on 2018-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagioProbatorio', '0002_estagioprobatorio_portaria_homologacao'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagioprobatorio',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.Servidor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagioProbatorio.EstagioProbatorio'),
        ),
    ]
