# Generated by Django 2.1 on 2018-09-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
