# Generated by Django 2.1 on 2018-09-03 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('siape',
                 models.CharField(max_length=9, unique=True, verbose_name='SIAPE')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('1', 'F'), ('2', 'M')], max_length=1)),
                ('tipo_sanguineo', models.CharField(
                    choices=[('1', 'A+'), ('2', 'B+'), ('3', 'AB+'), ('4', 'O+'), ('5', 'A-'), ('6', 'B-'),
                             ('7', 'AB-'), ('8', 'O-')], max_length=1)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('pis_pasep', models.CharField(max_length=13)),
                ('naturalidade', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_servidores')),
            ],
            options={
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('servidor',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='servidores.Servidor')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.IntegerField()),
                ('municipio', models.CharField(max_length=200)),
                ('servidor',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='servidores.Servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('titulacao', models.CharField(
                    choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Médio'), ('3', 'Técnico'), ('4', 'Tecnologico'),
                             ('5', 'Graduação'), ('6', 'Mestrado'), ('7', 'Doutorado'), ('8', 'Pós-doutorado ')],
                    max_length=1)),
                ('descricao', models.TextField(max_length=300)),
                ('local', models.CharField(max_length=200)),
                ('data_conclusao', models.DateField()),
                ('area_conhecimento', models.CharField(max_length=100)),
                ('servidor',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='servidores.Servidor')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria'),
        ),
    ]
