# Generated by Django 2.1 on 2018-09-11 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='dadosbancarios',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='pis_pasep',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='rg',
        ),
        migrations.AddField(
            model_name='servidor',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servidor',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_servidores', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='siape',
            field=models.CharField(max_length=7, unique=True, verbose_name='SIAPE'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'AB+'), ('4', 'O+'), ('5', 'A-'), ('6', 'B-'), ('7', 'AB-'), ('8', 'O-')], max_length=1, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='DadosBancarios',
        ),
        migrations.DeleteModel(
            name='Formacao',
        ),
    ]
