# Generated by Django 2.1 on 2018-08-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormacaoServidor',
            new_name='Formacao',
        ),
    ]
