# Generated by Django 2.1 on 2018-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_auto_20180924_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='data_exercicio',
            field=models.DateField(verbose_name='Data de Exercício'),
        ),
    ]
