# Generated by Django 2.1 on 2018-09-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_auto_20180910_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=1, verbose_name='Nível')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='cargo')),
            ],
        ),
    ]
