# Generated by Django 2.1 on 2018-09-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_auto_20180925_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='tempo_servico',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
