# Generated by Django 2.1 on 2018-09-11 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0005_auto_20180910_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=1, verbose_name='Nível')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servidores.Area'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servidores.Cargo'),
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='servidor',
            unique_together={('siape', 'nome', 'area'), ('siape', 'nome', 'cargo')},
        ),
    ]
