# Generated by Django 2.1 on 2018-09-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_auto_20180910_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='categoria',
            field=models.ForeignKey(default='1',on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Área'),
        ),
    ]
