# Generated by Django 2.1 on 2018-09-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0006_auto_20180926_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='tempo_servico',
        ),
    ]
