# Generated by Django 2.1 on 2018-11-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0007_remove_servidor_tempo_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'permissions': (('visualizar_servidor', 'Usuário pode visualizar cadastro de servidor'), ('atualizar_servidor', 'Usuário pode atualizar informações')), 'verbose_name_plural': 'Servidores'},
        ),
    ]
