# Generated by Django 2.1 on 2018-11-16 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidores', '0008_auto_20181115_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'permissions': (('cadastrar_servidor', 'Usuário pode cadastrar novo servidor'), ('visualizar_servidor', 'Usuário pode visualizar cadastro de servidor'), ('atualizar_servidor', 'Usuário pode atualizar informações'), ('deletar_servidor', 'Usuário pode deletar o cadastro do servidor')), 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AddField(
            model_name='servidor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
