# Generated by Django 2.1 on 2018-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campi', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sanguineo', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'AB+'), ('4', 'O+'), ('5', 'A-'), ('6', 'B-'), ('7', 'AB-'), ('8', 'O-')], max_length=1, verbose_name='Tipo Sanguíneo')),
                ('texto_email', models.TextField(max_length=2000)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campi.Campus')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria')),
            ],
        ),
    ]
