# Generated by Django 2.1 on 2018-10-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0007_remove_servidor_tempo_servico'),
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_email', models.TextField(max_length=2000)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campi.Campus')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Servidor')),
            ],
        ),
    ]
