# Generated by Django 2.1 on 2018-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoSanguineo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposanguineo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tiposanguineo',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'AB+'), ('4', 'O+'), ('5', 'A-'), ('6', 'B-'), ('7', 'AB-'), ('8', 'O-')], default='', max_length=1, verbose_name='Tipo Sanguíneo'),
            preserve_default=False,
        ),
    ]
