# Generated by Django 2.1 on 2018-09-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
        ('portarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressaoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_progressao', models.CharField(choices=[('1', 'Progressão por Desempenho Acadêmico'), ('2', 'Promoção na Carreira'), ('3', 'Aceleração de Promoção na Carreira')], max_length=1)),
                ('classe', models.CharField(choices=[('1', 'D I'), ('2', 'D II'), ('3', 'D III'), ('4', 'D IV'), ('5', 'Titular')], max_length=1)),
                ('nivel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('data_progressao', models.DateField()),
                ('data_prox_progressao', models.DateField(blank=True, null=True)),
                ('portaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portarias.Portaria')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Servidor')),
            ],
            options={
                'verbose_name_plural': 'Progressão Docente',
            },
        ),
        migrations.CreateModel(
            name='ProgressaoTAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_progressao', models.CharField(choices=[('1', 'Progressão por Mérito'), ('2', 'Promoção por Capacitação')], max_length=1)),
                ('nivel_capacitacao', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1, null=True)),
                ('padrao', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=1, null=True)),
                ('data_progressao', models.DateField()),
                ('data_prox_progressao', models.DateField(blank=True, null=True)),
                ('portaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portarias.Portaria')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Servidor')),
            ],
            options={
                'verbose_name_plural': 'Progressão TAE',
            },
        ),
        migrations.AlterUniqueTogether(
            name='progressaotae',
            unique_together={('servidor', 'tipo_progressao', 'padrao'), ('servidor', 'tipo_progressao', 'nivel_capacitacao')},
        ),
        migrations.AlterUniqueTogether(
            name='progressaodocente',
            unique_together={('servidor', 'tipo_progressao', 'classe', 'nivel')},
        ),
    ]
