# Generated by Django 2.1 on 2018-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_progressao_docente', models.CharField(blank=True, choices=[('1', 'Progressão por Desempenho Acadêmico'), ('2', 'Promoção na Carreira'), ('3', 'Aceleração de Promoção na Carreira')], max_length=2, null=True, verbose_name='Tipo de Progressão Docente')),
                ('tipo_progressao_tae', models.CharField(blank=True, choices=[('1', 'Progressão por Mérito'), ('2', 'Progressão por Capacitação')], max_length=1, null=True, verbose_name='Tipo de Progressão TAE')),
                ('classe_docente', models.CharField(blank=True, choices=[('1', 'D I'), ('2', 'D II'), ('3', 'D III'), ('4', 'D IV'), ('5', 'Titular')], max_length=1, null=True)),
                ('nivel_docente', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True)),
                ('nivel_capacitacao', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1, null=True)),
                ('padrao_tae', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=2, null=True)),
                ('data_progressao', models.DateField(verbose_name='Data Progressão')),
                ('carga_horaria_apresentada', models.IntegerField(verbose_name='Carga Horária Apresentada')),
                ('carga_horaria_exigida', models.IntegerField(verbose_name='Carga Horária Exigida')),
                ('carga_horaria_excedente', models.IntegerField(blank=True, null=True)),
                ('homologacao', models.FileField(blank=True, null=True, upload_to='homologacao', verbose_name='Comprovante')),
                ('data_prox_progressao', models.DateField(blank=True, null=True)),
                ('portaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portarias.Portaria')),
            ],
            options={
                'verbose_name_plural': 'Progressões',
            },
        ),
    ]
