# Generated by Django 2.1 on 2018-08-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portarias', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressaoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_progressao', models.CharField(choices=[('1', 'Progressão por Desempenho Acadêmico'), ('2', 'Promoção na Carreira'), ('3', 'Aceleração de Promoção na Carreira')], max_length=1)),
                ('data_progressao', models.DateField()),
                ('data_prox_progressao', models.DateField()),
                ('portaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portarias.Portaria')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Servidor')),
            ],
            options={
                'verbose_name_plural': 'Progressão Docente',
            },
        ),
    ]
