# Generated by Django 2.1 on 2018-09-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0008_auto_20180910_2340'),
        ('progressoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressaodocente',
            name='nivel',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progressaodocente',
            name='classe',
            field=models.CharField(choices=[('1', 'D I'), ('2', 'D II'), ('3', 'D III'), ('4', 'D IV'), ('5', 'Titular')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='progressaodocente',
            unique_together={('servidor', 'tipo_progressao', 'classe', 'nivel')},
        ),
    ]
