# Generated by Django 2.1 on 2018-11-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progressoes', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressao',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.Servidor'),
        ),
        migrations.AlterUniqueTogether(
            name='progressao',
            unique_together={('servidor', 'tipo_progressao_tae', 'nivel_capacitacao'), ('servidor', 'tipo_progressao_docente', 'classe_docente', 'nivel_docente'), ('servidor', 'tipo_progressao_tae', 'padrao_tae')},
        ),
    ]
