# Generated by Django 2.1 on 2018-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressao',
            name='tipo_progressao_docente',
            field=models.CharField(blank=True, choices=[('1', 'Progressão por Desempenho Acadêmico'), ('2', 'Promoção na Carreira'), ('3', 'Aceleração de Promoção na Carreira')], max_length=2, null=True),
        ),
    ]
