# Generated by Django 2.1 on 2018-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressao',
            name='carga_horaria_exigida',
            field=models.IntegerField(default=0, verbose_name='Carga Horária Exigida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progressao',
            name='carga_horaria_apresentada',
            field=models.IntegerField(verbose_name='Carga Horária Apresentada'),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='carga_horaria_excedente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='data_progressao',
            field=models.DateField(verbose_name='Data Progressão'),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='homologacao',
            field=models.FileField(blank=True, null=True, upload_to='homologacao', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='tipo_progressao_docente',
            field=models.CharField(blank=True, choices=[('1', 'Progressão por Desempenho Acadêmico'), ('2', 'Promoção na Carreira'), ('3', 'Aceleração de Promoção na Carreira')], max_length=2, null=True, verbose_name='Tipo de Progressão Docente'),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='tipo_progressao_tae',
            field=models.CharField(blank=True, choices=[('1', 'Progressão por Mérito'), ('2', 'Progressão por Capacitação')], max_length=1, null=True, verbose_name='Tipo de Progressão TAE'),
        ),
    ]
