# Generated by Django 2.1 on 2018-09-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
        ('progressoes', '0002_auto_20180903_2028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressaotae',
            unique_together={('servidor', 'tipo_progressao', 'nivel_capacitacao'), ('servidor', 'tipo_progressao', 'padrao')},
        ),
    ]
