# Generated by Django 2.1 on 2018-10-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressoes', '0003_auto_20181001_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressao',
            name='padrao_tae',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=2, null=True),
        ),
    ]
