# Generated by Django 2.1 on 2018-11-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressoes', '0005_auto_20181001_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressao',
            name='carga_horaria_apresentada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressao',
            name='carga_horaria_excedente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressao',
            name='homologacao',
            field=models.FileField(blank=True, null=True, upload_to='homologacao'),
        ),
    ]
